### ISSUE TITLE
dht22

### ISSUE THREAD

**Issue by apm1007** [glitch452/MMM-LocalTemperature#4]
ive tried to switch to this module but the temperature filed stays empty. im using dht 22
![image](https://user-images.githubusercontent.com/11927080/58747182-dfa2d800-8467-11e9-8a51-c5eda9bb68bc.png)
any idea whats wrong?
![image](https://user-images.githubusercontent.com/11927080/58747189-f77a5c00-8467-11e9-9820-14dd0dd47ab1.png)

**Comment by glitch452** [comment]
Hello, the reason that nothing shows up is because this module is primarily designed to send the temperature to the built-in 'currentweather' module, which can display the indoor temperature.  

In order to use this module to show the temperature and/or humidity, just set "showTemperature: true" and/or "showHumidity: true" in the config:
```js
{
    module: "MMM-LocalTemperature",
    position: "top_left",
    header: "Raum Temperatur",
    config: {
        sensorPin: 2,
        pinScheme: "BOARD",
        showTemperature: true
        showHumidity: true
    }
}
```
